name: Deploy to EC2 via SSH and Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Extract hostname or IP (remove user@)
          HOSTNAME=$(echo "${{ secrets.EC2_HOST }}" | sed 's/.*@//')
          ssh-keyscan -H $HOSTNAME >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_HOST }} << 'EOF'
            if [ -d "${{ secrets.DEPLOY_DIR }}/.git" ]; then
              cd ${{ secrets.DEPLOY_DIR }} && sudo git pull origin main
            else
              cd ${{ secrets.DEPLOY_DIR }}
              sudo git clone https://github.com/mykhailo-work/manata-cloudfront.git .
            fi
            sudo docker compose down
            docker image prune -a -f
            docker-compose down --volumes --remove-orphans
            sudo docker compose up -d
          EOF
